<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5d5ba7b55a803',
    'title' => __('Företagare berättar', 'investinhalland'),
    'fields' => array(
        0 => array(
            'key' => 'field_5d5bb15d22318',
            'label' => __('Företagare berättar', 'investinhalland'),
            'name' => 'company_stories',
            'type' => 'group',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5d5ba7b5eccff',
                    'label' => __('Mindre rubrik', 'investinhalland'),
                    'name' => 'sub_title',
                    'type' => 'text',
                    'instructions' => __('Mindre text som visas över den stora rubriken i sidhuvudet', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5d5ba7b5ecd2e',
                    'label' => __('Rubrik', 'investinhalland'),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => __('Stor rubrik som visas i sidhuvudet', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5d5ba7b5ecd57',
                    'label' => __('Utvald bild', 'investinhalland'),
                    'name' => 'featured_image',
                    'type' => 'image',
                    'instructions' => __('Välj en bakgrundsbild för sidhuvudet', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-foretagare-berattar',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Innehåller fält för sidan \'Företagare berättar\'\'',
));
}