<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5e54e5c8e45e8',
    'title' => __('Kontakt', 'investinhalland'),
    'fields' => array(
        0 => array(
            'key' => 'field_5e54e5d8cee1d',
            'label' => __('Rubrik', 'investinhalland'),
            'name' => 'contact_title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        1 => array(
            'key' => 'field_5e54e6ae56902',
            'label' => __('Kontaktperson', 'investinhalland'),
            'name' => 'contact_relationship',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'edit_in_rest' => 0,
            'post_type' => array(
                0 => 'contact',
            ),
            'taxonomy' => '',
            'filters' => array(
                0 => 'search',
                1 => 'post_type',
                2 => 'taxonomy',
            ),
            'elements' => '',
            'min' => 1,
            'max' => 1,
            'return_format' => 'object',
        ),
        2 => array(
            'key' => 'field_5e54e708ce77a',
            'label' => __('Länk 1', 'investinhalland'),
            'name' => 'contact_link_1',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'edit_in_rest' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5e54e72ace77b',
                    'label' => __('Länk', 'investinhalland'),
                    'name' => 'contact_link_1_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                ),
                1 => array(
                    'key' => 'field_5e54e743ce77c',
                    'label' => __('Länktext', 'investinhalland'),
                    'name' => 'contact_link_1_label',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
        3 => array(
            'key' => 'field_5e54e765ce77d',
            'label' => __('Länk 2', 'investinhalland'),
            'name' => 'contact_link_2',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'edit_in_rest' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5e54e765ce77e',
                    'label' => __('Länk', 'investinhalland'),
                    'name' => 'contact_link_2_url',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                ),
                1 => array(
                    'key' => 'field_5e54e765ce77f',
                    'label' => __('Länktext', 'investinhalland'),
                    'name' => 'contact_link_2_label',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/contact',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Fält för blocket kontakt i en artikel',
));
}