<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5d526d10f381b',
    'title' => __('Startsida', 'investinhalland'),
    'fields' => array(
        0 => array(
            'key' => 'field_5dc01bd37aafa',
            'label' => __('Startsida', 'investinhalland'),
            'name' => 'startpage',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'edit_in_rest' => 0,
            'layout' => 'block',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5dc015aca5de5',
                    'label' => __('Sidhuvud', 'investinhalland'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                1 => array(
                    'key' => 'field_5d63d46009bf1',
                    'label' => __('Rubrik (Över)', 'investinhalland'),
                    'name' => 'header_title_top',
                    'type' => 'text',
                    'instructions' => __('Text som visas överst, t.ex. "Nothing but"', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                2 => array(
                    'key' => 'field_5dc14313d23a2',
                    'label' => __('Rubrik (Under)', 'investinhalland'),
                    'name' => 'header_title_bottom',
                    'type' => 'text',
                    'instructions' => __('Text som visas unders, t.ex. "opportunities"', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                3 => array(
                    'key' => 'field_5e1daac0f9d67',
                    'label' => __('Bild 1', 'investinhalland'),
                    'name' => 'image_1',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                4 => array(
                    'key' => 'field_5e1daae8f9d68',
                    'label' => __('Bild 2', 'investinhalland'),
                    'name' => 'image_2',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                5 => array(
                    'key' => 'field_5dc015bfa5de6',
                    'label' => __('Utvalda artiklar', 'investinhalland'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                6 => array(
                    'key' => 'field_5dbffedf05f8d',
                    'label' => __('Rubrik', 'investinhalland'),
                    'name' => 'featured_articles_title',
                    'type' => 'text',
                    'instructions' => __('Text som visas innan orden som växlas. T.ex. Nothing but', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                7 => array(
                    'key' => 'field_5d63d4fd58ce9',
                    'label' => __('Inledande text', 'investinhalland'),
                    'name' => 'featured_articles_introduction_text',
                    'type' => 'wysiwyg',
                    'instructions' => __('T.ex Har du tänkt på att livet är en del av näringslivet? Om du vill bygga en verksamhet som håller och växer långsiktigt, måste livet utanför företaget också fungera. För dig, din familj och dina anställda. Därför ska du investera i Halland, den bästa livsplatsen.', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                ),
                8 => array(
                    'key' => 'field_5d63d53658cea',
                    'label' => __('Utvalda artiklar', 'investinhalland'),
                    'name' => 'featured_articles',
                    'type' => 'relationship',
                    'instructions' => __('Välj ut de artiklar som ska visas på startsidan.', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'post_type' => array(
                        0 => 'company_story',
                        1 => 'opportunity',
                        2 => 'fact',
                    ),
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'post_type',
                    ),
                    'elements' => '',
                    'min' => 3,
                    'max' => '',
                    'return_format' => 'object',
                ),
                9 => array(
                    'key' => 'field_5dc01618a5de7',
                    'label' => __('Möt företagarna', 'investinhalland'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 0,
                    'edit_in_rest' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                10 => array(
                    'key' => 'field_5dc01673a5de8',
                    'label' => __('Rubrik', 'investinhalland'),
                    'name' => 'featured_companies_title',
                    'type' => 'text',
                    'instructions' => __('Text som visas innan orden som växlas. T.ex. Nothing but', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                11 => array(
                    'key' => 'field_5dc0169aa5de9',
                    'label' => __('Inledande text', 'investinhalland'),
                    'name' => 'featured_companies_introduction_text',
                    'type' => 'wysiwyg',
                    'instructions' => __('T.ex Har du tänkt på att livet är en del av näringslivet? Om du vill bygga en verksamhet som håller och växer långsiktigt, måste livet utanför företaget också fungera. För dig, din familj och dina anställda. Därför ska du investera i Halland, den bästa livsplatsen.', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'default_value' => '',
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                ),
                12 => array(
                    'key' => 'field_5dc016bda5dea',
                    'label' => __('Utvalda artiklar', 'investinhalland'),
                    'name' => 'featured_companies',
                    'type' => 'relationship',
                    'instructions' => __('Välj ut de artiklar som ska visas på startsidan.', 'investinhalland'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'show_in_rest' => 1,
                    'edit_in_rest' => 0,
                    'post_type' => array(
                        0 => 'company_story',
                    ),
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'post_type',
                    ),
                    'elements' => '',
                    'min' => 3,
                    'max' => '',
                    'return_format' => 'object',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-startsida',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Information kopplad till startsidan.',
));
}