<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5d67dca6c2999',
    'title' => __('Summering', 'investinhalland'),
    'fields' => array(
        0 => array(
            'key' => 'field_5d67e217a3f0b',
            'label' => __('Titel', 'investinhalland'),
            'name' => 'title',
            'type' => 'text',
            'instructions' => __('Titel för hela summeringen, t.ex. "Om Raytelligence"', 'investinhalland'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        1 => array(
            'key' => 'field_5d67dce6118fd',
            'label' => __('Fråga', 'investinhalland'),
            'name' => 'question_1',
            'type' => 'text',
            'instructions' => __('T.ex. "Bransch"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        2 => array(
            'key' => 'field_5d6e2e004d7cb',
            'label' => __('Svar', 'investinhalland'),
            'name' => 'answer_1',
            'type' => 'textarea',
            'instructions' => __('T.ex. "Hälsoteknik"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
        3 => array(
            'key' => 'field_5d6e2d0e4d7c7',
            'label' => __('Fråga', 'investinhalland'),
            'name' => 'question_2',
            'type' => 'text',
            'instructions' => __('T.ex. "Bransch"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        4 => array(
            'key' => 'field_5d6e2e004d7ca',
            'label' => __('Svar', 'investinhalland'),
            'name' => 'answer_2',
            'type' => 'textarea',
            'instructions' => __('T.ex. "Hälsoteknik"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
        5 => array(
            'key' => 'field_5d6e2d0e4d7c6',
            'label' => __('Fråga', 'investinhalland'),
            'name' => 'question_3',
            'type' => 'text',
            'instructions' => __('T.ex. "Bransch"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        6 => array(
            'key' => 'field_5d6e2dff4d7c9',
            'label' => __('Svar', 'investinhalland'),
            'name' => 'answer_3',
            'type' => 'textarea',
            'instructions' => __('T.ex. "Hälsoteknik"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
        7 => array(
            'key' => 'field_5d6e2d0d4d7c5',
            'label' => __('Fråga', 'investinhalland'),
            'name' => 'question_4',
            'type' => 'text',
            'instructions' => __('T.ex. "Bransch"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        8 => array(
            'key' => 'field_5d6e2cbf6253a',
            'label' => __('Svar', 'investinhalland'),
            'name' => 'answer_4',
            'type' => 'textarea',
            'instructions' => __('T.ex. "Hälsoteknik"', 'investinhalland'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 1,
            'edit_in_rest' => 0,
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/summary',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Fält för faktarutan som visas i artiklar.',
));
}